import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/molecules/Navbar";
import { Roboto } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const roboto = Roboto({
  weight: "400",
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased relative`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
